### ISSUE TITLE
Can’t record my voice after upgrading to 25.7.3

### ISSUE THREAD

**Issue by abdnh** [ankitects/anki#4225]
> After upgrading 25.7.3, I can’t record my voice when learning, with the following message,
> Unable to record. Please ensure a microphone is connected, and Anki has permission to use the microphone. If other programs are using your microphone, closing them may help.
> Original error: ⁨’NoneType’ object has no attribute 'readyRead’⁩
> image630×204 11.4 KB

Originally reported on https://forums.ankiweb.net/t/cant-record-my-voice-after-upgrading-to-25-7-3/64453

I can reproduce this on Windows. Setting channel count to 2 is a quick fix (Qt considers the QAudioFormat object unsupported otherwise). The root cause of this is a change in Qt: the QAudioDevice::minimumChannelCount() method now returns 2. Try:
```python
from PyQt6.QtMultimedia import  QMediaDevices

device = QMediaDevices.defaultAudioInput()
print(device.minimumChannelCount())
```

**Comment by dae** [comment]
Thanks for digging into this! ❤️
